# Build stage

FROM bellsoft/liberica-openjdk-alpine:17 AS builder

WORKDIR /app

COPY . .
ARG MYSQL_DATABASE_URL
ARG MYSQL_DATABASE_USERNAME
ARG MYSQL_DATABASE_PASSWORD
ARG MONGODB_URI

ENV MYSQL_DATABASE_URL $MYSQL_DATABASE_URL
ENV MYSQL_DATABASE_USERNAME $MYSQL_DATABASE_USERNAME
ENV MYSQL_DATABASE_PASSWORD $MYSQL_DATABASE_PASSWORD
ENV MONGODB_URI $MONGODB_URI

RUN ./gradlew build

# Run stage

FROM bellsoft/liberica-openjdk-alpine:17

WORKDIR /app

COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]