name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub

        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build \
            --build-arg MYSQL_DATABASE_URL='${{ secrets.MYSQL_DATABASE_URL }}' \
            --build-arg MYSQL_DATABASE_USERNAME='${{ secrets.MYSQL_DATABASE_USERNAME }}' \
            --build-arg MYSQL_DATABASE_PASSWORD='${{ secrets.MYSQL_DATABASE_PASSWORD }}' \
            --build-arg MONGODB_URI='${{ secrets.MONGODB_URI }}' \
            -t capstone .

      - name: taging
        run: docker tag capstone:latest ${{ secrets.DOCKERHUB_USERNAME }}/capstone:latest

      - name: Push to Dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/capstone:latest

  deploy:

    runs-on: self-hosted
    needs: build

    steps:
      - name: Pull Docker image
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/capstone:latest
      - name: Delete Old docker container
        run: sudo docker rm -f capstone-container || true
      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name capstone-container ${{ secrets.DOCKERHUB_USERNAME }}/capstone